### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by NKID00** [NKID00/redstone-computer-utilities#7]
- Commands
  - [x] `/rcu`
  - [x] `/rcu new <interface name> [option...]`
  - [x] `/rcu remove <interface name...>`
  - [x] `/rcu info`
  - [x] `/rcu info interface`
  - [x] `/rcu info interface <interface name...>`
  - [x] `/rcu info script`
  - [x] `/rcu info script <script name...>`
  - [x] `/rcu run <script name> [argument...]`
  - [x] `/rcu reload`
  - [x] `/rcu lang`
  - [x] `/rcu lang <language>`
- [x] Selection Manager
- Interface Manager
  - [x] New
  - [x] Remove
  - [x] IO
  - [x] Event Callback
- Script Loader
  - [x] Communication
  - [x] Register
- [x] Timer 
- Script API
  - Script
    - [x] registerScript
    - [x] deregisterScript
    - [x] listScript
    - [x] invokeScript
  - Event Callback
    - [x] registerCallback
    - [x] deregisterCallback
    - [x] listCallback
    - [x] invokeCallback
  - Interface
    - [x] newInterface
    - [x] removeInterface
    - [x] listInterface
    - [x] infoInterface
    - [x] readInterface
    - [x] writeInterface
  - World
    - [ ] queryBlock
    - [ ] setBlock
    - [ ] emitNeighborUpdate
    - [ ] emitPostPlacement
    - [ ] queryEntity
    - [ ] summonEntity
    - [ ] killEntity
  - Miscellaneous
    - [x] gametime
    - [x] listPlayer
    - [ ] executeCommand
  - Logging
    - [x] info
    - [x] warn
    - [x] error
    - [x] sendInfo
    - [x] sendWarn
    - [x] sendError
- Script Event Callback
  - Script Lifecycle
    - [x] onScriptRegister
    - [x] onScriptReload
    - [x] onScriptRun
    - [x] onScriptInvoke
  - Gametick
    - [x] onGametickStart
    - [x] onGametickEnd
    - [x] onGametickStartDelay
    - [x] onGametickEndDelay
    - [x] onGametickStartClock
    - [x] onGametickEndClock
  - Interface
    - [x] onInterfaceUpdate
    - [x] onInterfaceUpdateImmediate
    - [x] onInterfaceRead
    - [x] onInterfaceWrite
    - [x] onInterfaceNew
    - [x] onInterfaceRemove
  - World
    - [ ] onBlockChange
    - [ ] onBlockNeighborUpdate
    - [ ] onBlockPostPlacement
    - [ ] onBlockRedstoneUpdate
    - [ ] onBlockRedstoneUpdateImmediate
- [x] Storage
- [x] Options
- I18n
  - [x] Loader
  - [x] English
  - [x] 简体中文
- Support for other mc versions
  - [x] 1.16
  - [x] 1.17
  - [x] 1.18
  - [x] 1.19
- Python Library
  - [x] Low-level API
  - [x] Low-level event callback
  - High-level API
    - [x] wait
    - [x] main function dispatcher
      - [ ] provide concrete interface instance with size etc.
    - [ ] auto data validator
